### ISSUE TITLE
best way to debug cron job

### ISSUE THREAD

**Issue by pkyeck** [redmatter/docker-vixie-cron#1]
what is the best way to debug the cron job when it is not working as expected?

**Comment by codemedic** [comment]
I usually get the app to log to a know place, or if the app logs to console, add redirection to capture the output into a file.
Then you can exec into the container to have a look at the file.
Always check the usual suspects; crontab formatting, and execute permission on the script.

Hope that helps.

**Comment by codemedic** [comment]
One more useful thing to do would be to exec into the container and run the script from console.
Keep in mind that the environment variables with which the script will be run under cron will be slightly different, unless you handpick the necessary variables and add them to `PRESERVE_ENV_VARS`

**Comment by pkyeck** [comment]
thank you - will try that
